env:
  global:
    - CC_TEST_REPORTER_ID=3c5c89aeb692d9e06f6bf1cbeb94c880137601df27f18694d12e7bf443202f8a
language: ruby
rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
language: node_js
node_js:
  - "8"
script:
  - npm run lintcss
  - npm run lintjs
  - npm test
after_success:
  - npm run coverage
# safelist
branches:
  only:
  - master
  - development